name: Create EC2 instance and terminate after 2 minutes

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Test/Prod'
        required: true
  push:
    branches:
      - main
      

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: 'arn:aws:iam::140561047603:role/github-action-role'
          aws-region: ap-southeast-1
      - name: Run shell script
        run: |
          chmod +x create-ec2-instance.sh
          ./create-ec2-instance.sh


